=== txteam/tx-parent/tx-components/tx-component-starter-report/src/main/java/com.tx.component/statistical/xml/statistical-1.0.xsd
<?xml version='1.0' encoding='UTF-8'?>
<xs:schema
        targetNamespace="http://wtms.com/xml/statistical-1.0.xsd"
        elementFormDefault="qualified"
        xmlns="http://wtms.com/xml/statistical-1.0.xsd"
        xmlns:xs="http://www.w3.org/2001/XMLSchema">
    <xs:element name="report">
        <xs:complexType>
            <xs:sequence>
                <xs:element type="xs:string" name="script"/>

                <xs:element type="conditions" name="conditions"/>
                <xs:element type="views" name="views"/>
                <xs:element type="sqlMappers" name="sqlMappers" />
            </xs:sequence>
            <xs:attribute type="xs:token" name="code" use="required"/>
            <xs:attribute name="type" use="required">
                <xs:simpleType>
                    <xs:restriction base="xs:string">
                        <xs:enumeration value="pagedListGrid"/>
                        <xs:enumeration value="listGrid"/>
                        <xs:enumeration value="EChart"/>
                    </xs:restriction>
                </xs:simpleType>
            </xs:attribute>
            <xs:attribute name="subType" use="optional">
                <xs:simpleType>
                    <xs:restriction base="xs:string">
                        <xs:enumeration value="Pie"/>
                        <xs:enumeration value="Line"/>
                        <xs:enumeration value="Lines"/>
                        <xs:enumeration value="Bars"/>
                        <xs:enumeration value="Maps"/>
                    </xs:restriction>
                </xs:simpleType>
            </xs:attribute>

            <xs:attribute type="xs:string" name="name"/>

        </xs:complexType>
    </xs:element>


    <xs:complexType name="conditions">
        <xs:sequence>
            <xs:element type="conditionItem" name="item" maxOccurs="unbounded" />
        </xs:sequence>
        <xs:attribute type="xs:string" name="cols" default="3"/>
    </xs:complexType>
    <xs:complexType name="views">
        <xs:sequence>
            <xs:element type="viewItem" name="item" maxOccurs="unbounded"/>
        </xs:sequence>
        <xs:attribute type="xs:string" name="sqlMapperId" use="required"/>
        <xs:attribute type="xs:string" name="fitColumns" use="optional"/>
        <!--<xs:attribute type="xs:string" name="statisticalDatasource" use="optional"/>-->
    </xs:complexType>
    <xs:complexType name="sqlMappers">
        <xs:sequence>
            <xs:element type="sqlMapper" name="sqlMapper" maxOccurs="unbounded"/>
        </xs:sequence>
    </xs:complexType>


    <xs:complexType name="viewItem">
        <xs:attribute type="xs:string" name="column" use="required"/>
        <xs:attribute type="xs:string" name="name" use="required"/>
        <xs:attribute type="xs:string" name="formatterFun" use="optional"/>
        <xs:attribute type="xs:string" name="statisticalType" use="optional"/>
        <xs:attribute type="xs:string" name="frozen" use="optional"/>

        <xs:attribute name="type" default="general">
            <xs:simpleType>
                <xs:restriction base="xs:string">
                    <xs:enumeration value="general"/>
                    <xs:enumeration value="date"/>
                    <xs:enumeration value="enum"/>
                    <xs:enumeration value="number"/>
                    <!--<xs:enumeration value="money"/>-->
                    <xs:enumeration value="boolean"/>
                    <xs:enumeration value="json"/>
                    <xs:enumeration value="alink"/>
                </xs:restriction>
            </xs:simpleType>
        </xs:attribute>
        <xs:attribute type="xs:string" name="enumClass" use="optional"/>
        <xs:attribute type="xs:string" name="refValue" use="optional"/>
    </xs:complexType>

    <xs:complexType name="sqlMapper">
        <xs:attribute type="xs:string" name="id" use="required"/>
        <xs:attribute type="xs:string" name="needStatisticalScript" use="optional"/>
        <xs:attribute type="xs:string" name="returnType" use="optional"/>
        <xs:attribute type="xs:string" name="parameterType" use="optional"/>
        <xs:attribute type="xs:string" name="datasourceId" use="optional"/>

        <xs:sequence>
            <xs:element type="if" name="if"/>
        </xs:sequence>

    </xs:complexType>
    <xs:complexType name="if">
        <xs:attribute type="xs:string" name="test" use="required"/>
    </xs:complexType>

    <xs:complexType name="conditionItem">
        <xs:attribute type="xs:string" name="value"/>
        <xs:attribute type="xs:string" name="sqlMapperId"/>
        <xs:attribute type="xs:string" name="labelName"/>
        <xs:attribute type="xs:string" name="labelValue"/>
        <xs:attribute type="xs:string" name="cssClass" use="optional"/>
        <xs:attribute type="xs:string" name="cssStyle" use="optional"/>
        <xs:attribute type="xs:string" name="enumClass"/>
        <!--  <xs:attribute type="xs:string" name="labelName"/> -->

        <xs:attribute type="xs:string" name="items"/>

        <xs:attribute type="xs:string" name="id" use="required"/>
        <xs:attribute type="xs:string" name="name" use="optional"/>
        <xs:attribute name="type" use="required">
            <xs:simpleType>
                <xs:restriction base="xs:string">
                    <xs:enumeration value="input"/>
                    <xs:enumeration value="input_date"/>
                    <xs:enumeration value="input_date_time"/>
                    <xs:enumeration value="select"/>
                </xs:restriction>
            </xs:simpleType>
        </xs:attribute>
        <xs:attribute type="xs:string" name="onClick" use="optional"/>
        <xs:attribute type="xs:string" name="readOnly" use="optional"/>
    </xs:complexType>

</xs:schema>

=== txteam/tx-parent/tx-components/tx-component-report/src/main/resources/statistical/grid/cashoutDetailReport.xml
<?xml version="1.0" encoding="UTF-8" ?>
<report
        xmlns="http://wtms.com/xml/statistical-1.0.xsd"
        xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
        xsi:schemaLocation="http://wtms.com/xml/statistical-1.0.xsd"
        code="cashoutDetailReport" type="pagedListGrid" name="提现明细报表"
>

    <!-- 页面附加的javascript:非必填 -->
    <script></script>

    <!-- cols：非必填： 默认为2 如果条件项小于3，则自动修改对应值，如果为3的倍数，则为3，如果为2的倍数则为2 -->
    <conditions cols="3">
        <item id="clientName" name="客户名称" value="" type="input"/>
        <item id="clientLoginName" name="交易账户" value="" type="input"/>
        <item cssClass="Wdate" name="开始时间" id="minCreateDate"
              type="input_date"
              cssStyle="width:38%"/>

        <item cssClass="Wdate" name="结束时间" type="input_date"
              id="maxCreateDate"
              cssStyle="width:38%"/>

        <item id="paymentChannel" name="交易渠道" type="select"

              labelName="name" items="{:====全部====}"/>

    </conditions>

    <!-- fitColumns:非必填，默认值为false -->
    <views fitColumns="false" sqlMapperId="queryTradingSummaryReport">
        <!-- formatter: -->
        <!-- width:非必填：默认值为 150 -->
        <!-- hidden:非必填：false -->
        <!-- frozen:非必填：false -->
        <item column="CLIENTNAME" name="客户名称"/>
        <item column="CLIENTLOGINNAME" name="客户登陆名"/>
        <!--<item column="PAYMENTCHANNEL" name="交易渠道" type="enum"-->
              <!--enumClass="com.tx.component.basicdata.model.PaymentChannelEnum" refValue="name"/>-->
        <item column="beforeSum" name="交易前金额" type="number"/>
        <item column="SUM" name="成交金额" type="number" statisticalType="sum"/>
        <item column="afterSum" name="交易后金额" type="number"/>
        <item column="BANKNAME" name="发卡行"/>
        <item column="bankCardNumber" name="提现卡号"/>
        <item column="CREATEDATE" name="交易时间"/>
    </views>

    <sqlMappers>
        <!-- datebaseId:非必填: 如果不填则databaseId为默认值 -->
        <sqlMapper id="queryTradingSummaryReport" datasourceId="">
            SELECT
            TCR.ID,
            TCR.CLIENTACCOUNTID,
            TCR.CLIENTACCOUNTITEMID,
            TCR.CLIENTID,
            TCR.applyTradingRecordSN,
            TCR.afterSum,
            TCR.beforeSum,
            TCR.poundageSum,
            DATE_FORMAT(TCR.CREATEDATE,'%Y-%m-%d %H:%i:%S') as CREATEDATE,
            TCR.LASTUPDATEDATE,
            TCR.REMARK,
            TCR.SERIALNUMBER,
            TCR. STATUS,
            abs(TCR.SUM) AS SUM,
            TCR.FACTSUM,
            TCR.TYPE,
            TCR.bankInfoId,
            TBK.`name` AS BANKNAME,
            TBK.`code` AS BANKCODE,
            TCR.bankCardNumber,
            TCR.PAYMENTCHANNEL,
            CBCI.USERNAME AS CLIENTNAME,
            CBCI.LOGINNAME AS CLIENTLOGINNAME
            FROM
            CLA_CASHOUT_RECORD TCR
            LEFT JOIN CL_CLIENT_INFO CBCI ON CBCI.ID = TCR.CLIENTID
            LEFT JOIN BD_BANKINFO TBK ON TCR.BANKINFOID = TBK.ID
            WHERE 1 =1
            <if test="@com.tx.core.util.OgnlUtils@isNotEmpty(clientAccountId)">
                <![CDATA[ AND TCR.CLIENTACCOUNTID = #{clientAccountId,jdbcType=VARCHAR} ]]>
            </if>
            <if test="@com.tx.core.util.OgnlUtils@isNotEmpty(status)">
                <![CDATA[ AND TCR.STATUS = #{status,jdbcType=VARCHAR} ]]>
            </if>
            <if test="@com.tx.core.util.OgnlUtils@isNotEmpty(commissionFee)">
                <![CDATA[ AND TCR.COMMISSIONFEE = #{commissionFee,jdbcType=BIT} ]]>
            </if>
            <if test="@com.tx.core.util.OgnlUtils@isNotEmpty(commissionFeeAmount)">
                <![CDATA[ AND TCR.COMMISSIONFEEAMOUNT = #{commissionFeeAmount,jdbcType=NUMERIC} ]]>
            </if>
            <if test="@com.tx.core.util.OgnlUtils@isNotEmpty(serialNumber)">
                <![CDATA[ AND TCR.SERIALNUMBER = #{serialNumber,jdbcType=VARCHAR} ]]>
            </if>
            <if test="@com.tx.core.util.OgnlUtils@isNotEmpty(tradingRecordId)">
                <![CDATA[ AND TCR.TRADINGRECORDID = #{tradingRecordId,jdbcType=VARCHAR} ]]>
            </if>
            <if test="@com.tx.core.util.OgnlUtils@isNotEmpty(type)">
                <![CDATA[ AND TCR.TYPE = #{type,jdbcType=VARCHAR} ]]>
            </if>
            <if test="@com.tx.core.util.OgnlUtils@isNotEmpty(clientAccountItemId)">
                <![CDATA[ AND TCR.CLIENTACCOUNTITEMID = #{clientAccountItemId,jdbcType=VARCHAR} ]]>
            </if>
            <if test="@com.tx.core.util.OgnlUtils@isNotEmpty(clientId)">
                <![CDATA[ AND TCR.CLIENTID = #{clientId,jdbcType=VARCHAR} ]]>
            </if>
            <if test="@com.tx.core.util.OgnlUtils@isNotEmpty(excludeId)">
                <![CDATA[ AND TCR.ID <> #{excludeId,javaType=java.lang.String} ]]>
            </if>
            <if test="@com.tx.core.util.OgnlUtils@isNotEmpty(paymentChannel)">
                <![CDATA[ AND TCR.PAYMENTCHANNEL = #{paymentChannel,jdbcType=VARCHAR} ]]>
            </if>
            <if test="@com.tx.core.util.OgnlUtils@isNotEmpty(clientName)">
                <![CDATA[ AND CBCI.USERNAME like concat('%', #{clientName} ,'%' ) ]]>
            </if>
            <if test="@com.tx.core.util.OgnlUtils@isNotEmpty(clientLoginName)">
                <![CDATA[ AND CBCI.LOGINNAME = #{clientLoginName,jdbcType=VARCHAR} ]]>
            </if>
            <if test="@com.tx.core.util.OgnlUtils@isNotEmpty(maxCreateDate)">
                <![CDATA[ AND TCR.CREATEDATE <  DATE_ADD(#{maxCreateDate},INTERVAL 1 DAY)  ]]>
            </if>
            <if test="@com.tx.core.util.OgnlUtils@isNotEmpty(minCreateDate)">
                <![CDATA[ AND TCR.CREATEDATE >= #{minCreateDate,jdbcType=TIMESTAMP} ]]>
            </if>
            ORDER BY TCR.CREATEDATE DESC
        </sqlMapper>
    </sqlMappers>


</report>

=== txteam/tx-parent/tx-components/tx-component-starter-report/src/main/resources/statistical/grid/cashoutDetailReport.xml
<?xml version="1.0" encoding="UTF-8" ?>
<report
        xmlns="http://wtms.com/xml/statistical-1.0.xsd"
        xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
        xsi:schemaLocation="http://wtms.com/xml/statistical-1.0.xsd"
        code="cashoutDetailReport" type="pagedListGrid" name="提现明细报表"
>

    <!-- 页面附加的javascript:非必填 -->
    <script></script>

    <!-- cols：非必填： 默认为2 如果条件项小于3，则自动修改对应值，如果为3的倍数，则为3，如果为2的倍数则为2 -->
    <conditions cols="3">
        <item id="name" name="店铺名称" value="" type="input"/>
        <item id="price" name="价格" value="" type="input"/>


    </conditions>

    <!-- fitColumns:非必填，默认值为false -->
    <views fitColumns="false" sqlMapperId="queryTradingSummaryReport">
        <!-- formatter: -->
        <!-- width:非必填：默认值为 150 -->
        <!-- hidden:非必填：false -->
        <!-- frozen:非必填：false -->
        <item column="name" name="店铺名称" data="name"/>
        <item column="price" name="价格" data="price"/>
        <item column="amount" name="金额" type="number" data="amount"/>
        <item column="phone" name="电话" type="number" data="phone" />
        <item column="quantity" name="数量" statisticalType="sum" data="quantity"/>

    </views>

    <sqlMappers>
        <!-- datebaseId:非必填: 如果不填则databaseId为默认值 -->
        <sqlMapper id="queryTradingSummaryReport" datasourceId="">
            SELECT
            o.amount,
            o.createdDate,
            b.`name`,
            o.price,
            o.phone,
            o.quantity
            FROM
            orders o
            LEFT JOIN business b ON o.business_id = b.id
        </sqlMapper>
    </sqlMappers>


</report>
